<a href="https://colab.research.google.com/github/alyadevii/Tugas-Digital-Skola---Data-Science/blob/main/HW4_Exploring_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
paid_transaction = pd.read_excel("/content/drive/MyDrive/Data/Homework-DataFrame-Dataset.xlsx", sheet_name = "Paid-Transaction")
paid_transaction

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0
1,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
2,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
3,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
4,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
11995,20171201,201712012704898,Fitrah,gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300.0,0,0.0
11996,20171203,201712032723513,Djebeng,Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0.0,0,0.0
11997,20171204,201712042740205,Amik,Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800.0,0,0.0
11998,20171207,201712072778621,Anna,asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0.0,0,0.0
11999,20171205,201712052746101,nidyah,ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000.0,17000,0.0

In [ ]:
seller = pd.read_excel("/content/drive/MyDrive/Data/Homework-DataFrame-Dataset.xlsx", sheet_name = "Seller")
seller

          Order Number        Seller
0      201707209929420  Global Phone
1      201707129550097        E-shop
2      201707039056021   twelven com
3      201707099376522      GRAMEDIA
4      201707028956707        E-Bold
...                ...           ...
11995  201712042733301        E-Bold
11996  201711292684084  Luckykorea88
11997  201712072774578      GAU SHOP
11998  201712032722038   Farida Toko
11999  201712112833370   Mullia Cell

[12000 rows x 2 columns]

Penggabungan sheet “Paid-Transaction” dan “Seller” di berkas excel “Homework-DataFrame-Dataset.xlsx”

In [ ]:
df_merge = pd.merge(paid_transaction, seller, on = "Order Number", how= "left")
df_merge

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,Seller
0,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0,Babymaniashop
1,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0,E-Bold
2,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0,XLmystore
3,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0,Ennwen Online Store
4,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...
11995,20171201,201712012704898,Fitrah,gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300.0,0,0.0,XLmystore
11996,20171203,201712032723513,Djebeng,Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0.0,0,0.0,XLmystore
11997,20171204,201712042740205,Amik,Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800.0,0,0.0,Kreta Chips
11998,20171207,201712072778621,Anna,asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0.0,0,0.0,Erafone.com
11999,20171205,201712052746101,nidyah,ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000.0,17000,0.0,Serbu Seller

Pembuatan kolom baru bernama “Full Name” dan sisipkan kolom tersebut setelah kolom “Last
Name”

In [ ]:
df_merge ['Full Name'] = df_merge['First Name'] + ' ' + df_merge ['Last Name']
df_merge.insert (4, "Full Name", df_merge.pop("Full Name"))
df_merge

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,Seller
0,20170724,201707240088517,elvride,aries,elvride aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0,Babymaniashop
1,20170701,201707018889790,BASIR,Ninuk,BASIR Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0,E-Bold
2,20170707,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0,XLmystore
3,20170720,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0,Ennwen Online Store
4,20170722,201707220002354,rizal,Tamba,rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,20171201,201712012704898,Fitrah,gina,Fitrah gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300.0,0,0.0,XLmystore
11996,20171203,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0.0,0,0.0,XLmystore
11997,20171204,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800.0,0,0.0,Kreta Chips
11998,20171207,201712072778621,Anna,asih,Anna asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0.0,0,0.0,Erafone.com
11999,20171205,201712052746101,nidyah,ayi,nidyah ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000.0,17000,0.0,Serbu Seller

Pengubahan Nama lengkap menggunakan “title case”

In [ ]:
df_merge['Full Name']=df_merge['Full Name'].str.title()
df_merge

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Babymaniashop
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,E-Bold
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,XLmystore
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Ennwen Online Store
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2017-12-01,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,33000,2300.0,0,0.0,XLmystore
11996,2017-12-03,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,57500,0.0,0,0.0,XLmystore
11997,2017-12-04,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,69000,4800.0,0,0.0,Kreta Chips
11998,2017-12-07,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,75000,0.0,0,0.0,Erafone.com
11999,2017-12-05,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,92000,20000.0,17000,0.0,Serbu Seller

Pembuatan sebuah kolom setelah kolom “Seller Discount” dengan nama
“GMV”

In [ ]:
df_merge ['GMV'] = df_merge['Transaction Amount'] - df_merge['Seller Discount'] + df_merge['Delivery Fee']
df_merge.insert (9, "GMV", df_merge.pop("GMV"))
df_merge

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
0,20170724,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Babymaniashop
1,20170701,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,E-Bold
2,20170707,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,XLmystore
3,20170720,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Ennwen Online Store
4,20170722,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,20171201,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,33000,2300.0,0,0.0,XLmystore
11996,20171203,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,57500,0.0,0,0.0,XLmystore
11997,20171204,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,69000,4800.0,0,0.0,Kreta Chips
11998,20171207,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,75000,0.0,0,0.0,Erafone.com
11999,20171205,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,92000,20000.0,17000,0.0,Serbu Seller

Kelompokkan setiap Meta Category menjadi 2 group

In [ ]:
df_merge['Meta Category'].unique()

array(['Babies/ Kids', 'Service/ Mokado', 'Fashion', 'Gadget/ Komputer',
       'Beauty/ Health', 'Home/ Food', 'Sports/ Hobi/ Otomotif',
       'Elektronik'], dtype=object)

In [ ]:
category_group_mapping = {'Babies/ Kids':'Group 2',
                          'Service/ Mokado':'Group 2',
                          'Fashion':'Group 1',
                          'Gadget/ Komputer':'Group 2',
                          'Beauty/ Health':'Group 1',
                          'Home/ Food':'Group 1',
                          'Sports/ Hobi/ Otomotif':'Group 1',
                          'Elektronik':'Group 1'}

In [ ]:
df_merge ['Category'] = df_merge['Meta Category'].map(category_group_mapping)
df_merge.insert (6, "Category", df_merge.pop("Category"))
df_merge

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller,Month
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Group 2,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Babymaniashop,2017-07
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Group 2,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,E-Bold,2017-07
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,Group 2,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,XLmystore,2017-07
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Group 1,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Ennwen Online Store,2017-07
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Group 2,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Media Gadget,2017-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2017-12-01,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,Group 2,"Xtra Combo 12GB, 30hr",333000,300000,33000,2300.0,0,0.0,XLmystore,2017-12
11996,2017-12-03,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,Group 2,"Xtra Combo 12GB, 30hr",280000,222500,57500,0.0,0,0.0,XLmystore,2017-12
11997,2017-12-04,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Group 1,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,69000,4800.0,0,0.0,Kreta Chips,2017-12
11998,2017-12-07,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Group 2,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,75000,0.0,0,0.0,Erafone.com,2017-12
11999,2017-12-05,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,Group 2,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,92000,20000.0,17000,0.0,Serbu Seller,2017-12

Pembuatan DataFrame “Paid-Transaction” untuk menampilkan
jumlah total nilai GMV per-bulan untuk setiap group.

In [ ]:
df_merge['Month'] = df_merge['Paid Date'].dt.to_period('M')
pivot_gmv_per_month_per_group = pd.pivot_table(
    data= df_merge,
    index='Month',
    columns='Category',
    values='GMV',
    aggfunc='sum')
pivot_gmv_per_month_per_group

Category    Group 1    Group 2
Month
2017-07   151813800  226324600
2017-08    96420900  346968900
2017-09   270659300  184609800
2017-10   119863000  145283800
2017-11   265649700  324211700
2017-12   134399800  448388300

Python statement untuk mencari Seller mana yang memiliki total nilai GMV paling tinggi
di bulan Agustus 2017

In [ ]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Paid Date           12000 non-null  int64
 1   Order Number        12000 non-null  int64
 2   First Name          11996 non-null  object
 3   Last Name           11996 non-null  object
 4   Full Name           11992 non-null  object
 5   Meta Category       12000 non-null  object
 6   Product Name        12000 non-null  object
 7   Transaction Amount  12000 non-null  int64
 8   Seller Discount     12000 non-null  int64
 9   GMV                 12000 non-null  int64
 10  Sales Discount      12000 non-null  float64
 11  Delivery Fee        12000 non-null  int64
 12  Other Discount      12000 non-null  float64
 13  Seller              12000 non-null  object
dtypes: float64(2), int64(6), object(6)
memory usage: 1.3+ MB

In [ ]:
df_merge['Paid Date'] = pd.to_datetime(df_merge['Paid Date'].astype(str), format='%Y%m%d')
df_merge

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
0,2017-07-24,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Babymaniashop
1,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,E-Bold
2,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,XLmystore
3,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Ennwen Online Store
4,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2017-12-01,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,33000,2300.0,0,0.0,XLmystore
11996,2017-12-03,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,57500,0.0,0,0.0,XLmystore
11997,2017-12-04,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,69000,4800.0,0,0.0,Kreta Chips
11998,2017-12-07,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,75000,0.0,0,0.0,Erafone.com
11999,2017-12-05,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,92000,20000.0,17000,0.0,Serbu Seller

In [ ]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Paid Date           12000 non-null  datetime64[ns]
 1   Order Number        12000 non-null  int64
 2   First Name          11996 non-null  object
 3   Last Name           11996 non-null  object
 4   Full Name           11992 non-null  object
 5   Meta Category       12000 non-null  object
 6   Product Name        12000 non-null  object
 7   Transaction Amount  12000 non-null  int64
 8   Seller Discount     12000 non-null  int64
 9   GMV                 12000 non-null  int64
 10  Sales Discount      12000 non-null  float64
 11  Delivery Fee        12000 non-null  int64
 12  Other Discount      12000 non-null  float64
 13  Seller              12000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(6)
memory usage: 1.3+ MB

In [ ]:
df_agustus = df_merge[df_merge['Paid Date']. dt.to_period('M') == '2017-08']
df_agustus

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
1102,2017-08-08,201708080665846,lisa,Ervin,Lisa Ervin,Babies/ Kids,Selimut Double Fleece Carters 100 cm x 75 cm -...,16000,6100,18900,0.0,9000,0.0,Venna Shop
1103,2017-08-13,201708120799765,chrysdian,Yantie,Chrysdian Yantie,Fashion,NEW ITEM // LADIES SHIRT V COLLAR // 7 Warna /...,250000,91000,169000,11100.0,10000,0.0,shop and save fashion
1104,2017-08-10,201708100736231,lidya,Ria,Lidya Ria,Service/ Mokado,Pulsa Telkomsel REG 200.000,75000,5000,70000,0.0,0,0.0,E-Bold
1105,2017-08-13,201708130817233,Novi,saif,Novi Saif,Fashion,Celana Kulot Panjang Wanita / Bahan Spandek Uk...,125000,0,125000,0.0,0,0.0,Grosir Baju Anak
1106,2017-08-29,201708291193006,gading,Febe,Gading Febe,Fashion,Ransel Wanita 816,35000,0,35000,0.0,0,0.0,hs grosir tas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5599,2017-08-23,201708231065862,Grace,Widjatmoko,Grace Widjatmoko,Service/ Mokado,Indosat REG 25000,125000,30000,95000,6600.0,0,0.0,MOBILEPULSA APP
5600,2017-08-11,201708110778087,YUWANDARI,sucipto,Yuwandari Sucipto,Babies/ Kids,Paw Patrol Parking Lot Winter Rescue,150000,45000,105000,7200.0,0,0.0,BABY WISH
5601,2017-08-06,201708060595560,Shelly,sucipto,Shelly Sucipto,Service/ Mokado,Telkomsel Data 100.000,100000,30000,70000,4800.0,0,0.0,MOBILEPULSA APP
5602,2017-08-15,201708150879873,feriyana,yasin,Feriyana Yasin,Service/ Mokado,Pulsa Bolt Isi Ulang Otomatis 100000,100000,30000,80000,4800.0,10000,0.0,MOBILEPULSA APP
5603,2017-08-29,201708271154867,rara,Rio,Rara Rio,Fashion,[ONS 0102] NEW ARRIVAL !! KEMEJA WANITA - BOYF...,100000,40000,60000,4200.0,0,0.0,SHOP THE BRANDED

In [ ]:
df_gmv_sum_agustus = df_agustus.groupby(['Seller']).agg({'GMV': 'sum'})
df_gmv_sum_agustus.sort_values(by='GMV', ascending=False).head(1)

                       GMV
Seller
MOBILEPULSA APP  127241500

Python statement untuk mencari Count Seller banyaknya transaksi
di bulan September 2017 untuk Category “Fashion”.

In [ ]:
df_september = df_merge[df_merge['Paid Date']. dt.to_period('M') == '2017-09']
df_september

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
2472,2017-09-24,201709241731825,lian,teguh,Lian Teguh,Service/ Mokado,Tri Nambah Masa Aktif 4bulan Three Extra 120ha...,50000,26000,24000,0.0,0,0.0,Toko Lariz
2473,2017-09-13,201709131546157,Ika,Sumardani,Ika Sumardani,Gadget/ Komputer,Stylish STPU Soft Case Samsung Galaxy Note 3 N...,158000,102700,55300,0.0,0,0.0,sarunghape
2474,2017-09-02,201709021277460,tesya,Bayu,Tesya Bayu,Fashion,Bralette Tali 6/ Active BRA tali 6/ Black & Wh...,158000,102700,55300,0.0,0,0.0,duta shop
2475,2017-09-24,201709241729094,Nuril,aji,Nuril Aji,Home/ Food,LUNA CONSOLE (TANPA KURSI RIAS),32000,0,41000,0.0,9000,0.0,THE OLIVE HOUSE
2476,2017-09-20,201709201670584,ladira,Anthony,Ladira Anthony,Fashion,BATIK CULLOTE - SKIRT - SKORT - Kulot Batik - ...,150000,107000,43000,3000.0,0,0.0,EVERCLOTH_ID
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8461,2017-09-11,201709111504002,dini,harisjaya,Dini Harisjaya,Home/ Food,Pocari Sweat 2L [1 Karton isi 6 Botol],69000,31000,38000,1500.0,0,0.0,Amerta Indah Otsuka
8462,2017-09-28,201709281796688,Miftakhul,Caroline,Miftakhul Caroline,Home/ Food,Jam Dinding Unik - Nail Your Art BlackMapleNum...,124800,56100,68700,0.0,0,0.0,Viventi Living
8463,2017-09-15,201709151590044,renie,aditya,Renie Aditya,Home/ Food,[1+3] Jepitan Sprei Sheet Grippers - Pengait U...,41600,18700,22900,0.0,0,0.0,GudangUnik
8464,2017-09-18,201709181638780,Silvia,Fabiyola,Silvia Fabiyola,Fashion,CELANA PANJANG BAHAN FORMAL/CELANA KERJA PRIA ...,41600,18700,22900,0.0,0,0.0,M-line
8465,2017-09-04,201709041347404,Hartanto,eddylianto,Hartanto Eddylianto,Service/ Mokado,Promo Paket Data Internet Indosat Freedom Comb...,41600,18700,22900,0.0,0,0.0,Plaza Cell

In [ ]:
df_september['Meta Category'].unique()

array(['Service/ Mokado', 'Gadget/ Komputer', 'Fashion', 'Home/ Food',
       'Elektronik', 'Beauty/ Health', 'Sports/ Hobi/ Otomotif',
       'Babies/ Kids'], dtype=object)

In [ ]:
fashion = df_september[df_september['Meta Category'] == 'Fashion']

In [ ]:
fashion_count = pd.pivot_table(data= fashion, index= 'Seller', values= 'Transaction Amount', aggfunc= 'count')
fashion_count.sort_values(by='Transaction Amount', ascending=False).head(1)

           Transaction Amount
Seller
tokoaqila                  31